#!/bin/bash

AXIOM_HOME="$HOME/proyectos/AxiomOS"

COMMAND="$1"
shift || true

case "$COMMAND" in

    new)
        "$AXIOM_HOME/scripts/create_project.sh" "$@"
        ;;

    doctor)
        "$AXIOM_HOME/scripts/doctor.sh"
        ;;

    info)
        "$AXIOM_HOME/scripts/info.sh"
        ;;

    run)
        "$AXIOM_HOME/scripts/run.sh"
        ;;

    install)
        "$AXIOM_HOME/scripts/install_project.sh"
        ;;

    build)
        "$AXIOM_HOME/scripts/build.sh"
        ;;

    clean)
        "$AXIOM_HOME/scripts/clean.sh"
        ;;

    open)
        "$AXIOM_HOME/scripts/open.sh"
        ;;

    help|"")
        echo "AxiomOS CLI"
        echo
        echo "Usage:"
        echo "  axiom new <type> <name>"
        echo "  axiom doctor"
        echo "  axiom info"
        echo "Examples:"
        echo "  axiom new latex InformeFisica"
        echo "  axiom new python MinimosCuadrados"
        ;;

    *)
        echo "Unknown command: $COMMAND"
        echo "Run: axiom help"
        exit 1
        ;;

esac