PROFILE_APT_PACKAGES=(
    git
    octave
    gnuplot
    maxima
    texlive-full

    sqlite3
    sqlitebrowser
    nodejs
    npm
)

PROFILE_PIP_PACKAGES=(
    numpy
    scipy
    sympy
    matplotlib
    pandas
    jupyter

    pytest
    black
    mypy
)